# Generated by Django 3.2.3 on 2021-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(height_field=200, upload_to='images', width_field=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
