# Generated by Django 3.2.3 on 2021-06-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfollio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='Project',
        ),
    ]
