# Generated by Django 3.2.3 on 2021-06-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfollio', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
